apiVersion: v1
kind: ConfigMap
metadata:
  name: app-backend-config
  labels:
    app: app-backend
data:
  SERVER_NAME: server
  SERVER_HOST: http://localhost
  MONGODB_USER: root
  MONGODB_PASS: rootpassword
  MONGODB_HOST: mongo
  MONGODB_PORT: 27017
  MONGODB_DB: appointments
  
