apiVersion: v1
kind: ConfigMap
metadata:
  name: app-backend-config
  labels:
    app: app-backend
data:
  SERVER_NAME: server
  SERVER_HOST: "http://localhost"
  MONGODB_USER: "adminuser"
  MONGODB_PASS: "password123"
  MONGODB_HOST: "mongo-svc"
  MONGODB_PORT: "27017"